### ISSUE TITLE
Prefix static files directories

### ISSUE THREAD

**Issue by ppfeufer** [Maestro-Zacht/allianceauth-pve#6]
### Current

Your static files are in `static/css/` and `static/js/`, which results them being (after `collectstatic` is run) in `/var/www/static/css/` and `/var/www/static/js/`.

This is not good behaviour, since this is pretty much the "global" directory.

### Solution

Move your static files to `static/allianceauth_pve/css/` and `static/allianceauth_pve/js/` respectively. This way they will end up in `/var/www/static/allianceauth_pve/css/` and `/var/www/static/allianceauth_pve/js/` and cannot be accidentally overridden by another app which might use the same file names, since you now use your own directory.

**Comment by Maestro-Zacht** [comment]
Done in v1.2.1, thank you for pointing out this issue :)
