### ISSUE TITLE
When searching for characters, on entry screen, nothing comes up.

### ISSUE THREAD

**Issue by bmoe872** [Maestro-Zacht/allianceauth-pve#9]
* allianceauth-pve version: 1.4.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description

Trying to setup a new entry within a rotation, and when I search for a character - nothing comes up. I keep getting "No Results" despite having an entire corp full of people in the site. 

Geroni is my character, and I'm logged in. Screenshot attached shows I'm logged in, and that searching for "Geroni" is bringing no results:
![Screen Shot 2022-09-02 at 1 02 11 PM](https://user-images.githubusercontent.com/3431862/188220439-f533fd6b-55c5-4e37-b4ba-0b5fa1dd0ed0.png)

Additionally nothing is coming up in the browser console, so I'm not seeing any error.

**Comment by Maestro-Zacht** [comment]
Only characters with the `access_pve` permission can be added to entries and will be shown by the search.

I've looked at it and in admin page the permission only shows the long description and not the name I wrote in the readme. I'll make the long description start with the name I put in the readme on next patch, for now the permission you are looking for is the first one in this pic
![image](https://user-images.githubusercontent.com/61846068/188222597-58d9961c-e108-4f91-bab0-095f9ad6ba65.png)

**Comment by bmoe872** [comment]
Was just coming back to say I figured it out after re-reading the docs. Totally missed that part so my bad!! Thank you for the prompt reply, and thank you for making this! Much appreciated. 🙌

**Comment by Maestro-Zacht** [comment]
No problem, hope you'll find this tool useful :P
If you have any other issue/suggestion feel free to ask here or on discord
